//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AttributGrp
    {
        public AttributGrp()
        {
            this.AttributItem = new HashSet<AttributItem>();
        }
    
        public int AttributGrpId { get; set; }

        [Display(Name="نام گروه فیلتر")]
        [StringLength(50, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string Name { get; set; }

        [Display(Name = "نوع گروه ")]
        public string Attr_type { get; set; }

        [Display(Name = " گروه محصول")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int ProductGroupId { get; set; }

        public virtual ProductGroup ProductGroup { get; set; }
        public virtual ICollection<AttributItem> AttributItem { get; set; }
    }
}
