//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    
    public partial class AttributItem
    {
        public AttributItem()
        {
            this.Product_Attribut = new HashSet<Product_Attribut>();
        }
    
        public int AttributItemId { get; set; }


        [Display(Name = "نام فیلتر ")]
        [StringLength(50, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string Name { get; set; }

        [Display(Name = "نام به انگلیسی ")]
        [StringLength(50, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string value { get; set; }

        [Display(Name = "کلید فیلتر ")]
        [StringLength(50, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string idfilter { get; set; }

        [Display(Name = "گروه فیلتر")]
        public int AttributGrpId { get; set; }
        public virtual AttributGrp AttributGrp { get; set; }
        public virtual ICollection<Product_Attribut> Product_Attribut { get; set; }
    }
}
