//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class chartPost
    {
        public chartPost()
        {
            this.TicketGroup = new HashSet<TicketGroup>();
            this.User = new HashSet<User>();
        }
    
        public int chartPostId { get; set; }
        public string Postduty { get; set; }
        public virtual ICollection<TicketGroup> TicketGroup { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
