//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class City
    {
        public City()
        {
            this.Store = new HashSet<Store>();
        }
    
        public int CityId { get; set; }

        public string CityName { get; set; }   

        public byte[] CityIcon { get; set; }

        public int StateId { get; set; }
    
        public virtual State State { get; set; }

        public virtual ICollection<Store> Store { get; set; }
    }
}
