//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ComponentDesign
    {
        public int ComponentdesignId { get; set; }

        public int ComponentId { get; set; }

        public string Design { get; set; }

        public virtual Component Component  { get; set; }

    }
}
