//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ContactModule
    {
        public ContactModule()
        {
            this.ContactPerson = new HashSet<ContactPerson>();
        }

        public int ContactModuleId { get; set; }

        public string Email { get; set; }

        public string PhoneNum { get; set; }

        public string MobileNum { get; set; }

        public string Address { get; set; }

        public string PostCode { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        public Module Module { get; set; }

        public virtual ICollection<ContactPerson> ContactPerson { get; set; }
    }
}
