    //------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DetailItem
    {
        public DetailItem()
        {
            this.ProductDetail = new HashSet<ProductDetail>();
            this.RequestDetail = new HashSet<RequestDetail>();
        }
    
        public int DetailItemId { get; set; }

        [Display(Name ="نام خصوصیت")]
        [StringLength(50, ErrorMessage = "لطفا تعداد کاراکترها را رعایت کنید", MinimumLength = 3)]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string DetailTitle { get; set; }

        public string DetailType { get; set; }

        [Display(Name = "گروه خصوصیت")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int DetailGroupId { get; set; }

        public virtual DetailGroup DetailGroup { get; set; }

        public virtual ICollection<ProductDetail> ProductDetail { get; set; }

        public virtual ICollection<RequestDetail> RequestDetail { get; set; }
    }
}
