//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Menu
    {
        public Menu()
        {
            this.ModulePage = new HashSet<ModulePage>();
        }
    
        public int MenuId { get; set; }

        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [StringLength(50, ErrorMessage = "لطفا تعداد کاراکترها را رعایت کنید", MinimumLength = 3)]
        [Display(Name = "عنوان منو")]
        public string MenuTitle { get; set; }

        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [StringLength(50, ErrorMessage = "لطفا تعداد کاراکترها را رعایت کنید", MinimumLength = 3)]
        [Display(Name = "نام مستعار")]
        [Remote("UniquePageName", "Menus", ErrorMessage = "این نام از قبل وجود دارد", AdditionalFields = "MenuId")]
        public string PageName { get; set; }

        public Nullable<int> Depth { get; set; }

        [StringLength(100)]
        public string Path { get; set; }

        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [Display(Name = "وضعیت گزینه منو")]
        public Nullable<bool> IsActive { get; set; }

        [Display(Name = "ترتیب منوها")]
        public Nullable<int> DisplayOrder { get; set; }

        [Display(Name = "والد گزینه منو")]
        public Nullable<int> ParentId { get; set; }

        [Display(Name = "توضیحات صفحه")]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [StringLength(100)]
        [Display(Name = "نوع آیتم منو")]
        public string PageType { get; set; }

        [Display(Name = "محتوای صفحه منو")]
        [StringLength(100)]
        public string PageContetnt { get; set; }

        [Display(Name = "موقعیت منو")]
        public int MenuGroupId { get; set; }
    
        public virtual MenuGroup MenuGroup { get; set; }
        public virtual ICollection<ModulePage> ModulePage { get; set; }
    }
}
