//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MenuGroup
    {
        public MenuGroup()
        {
            this.Menu = new HashSet<Menu>();
            this.MenuModule = new HashSet<MenuModule>();
        }
    
        public int MenuGroupId { get; set; }

        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [StringLength(50, ErrorMessage = "لطفا تعداد کاراکترها را رعایت کنید", MinimumLength = 3)]
        [Display(Name = "عنوان گروه منو")]
        public string MenuTitile { get; set; }

        [Display(Name = "نوع منو")]
        [StringLength(50)]
        public string MenuType { get; set; }

        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [Display(Name = "وضعیت گرووه")]
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual ICollection<MenuModule> MenuModule { get; set; }
    }
}
