//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class Message : TimeEntity
    {
        public int MessageId { get; set; }

        //[InverseProperty("UsersFrom")]
        [Display(Name = "فرستنده")]
        public Nullable<int> FromUser { get; set; }

        //[InverseProperty("UsersTo")]
        [Display(Name = "گیرنده")]
        public Nullable<int> ToUser { get; set; }

        [Display(Name = "موضوع پیام")]
        [StringLength(50, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string Subject { get; set; }

        [Display(Name = "محتوای پیام")]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string ContentMessage { get; set; }

        [Display(Name = "ایمیل")]
        [StringLength(100, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        [DataType(DataType.EmailAddress,ErrorMessage ="لطفا ایمیل را به درستی وارد کنید")]
        public string Email { get; set; }

        public string Mobile { get; set; }

        [MaxLength(10)]
        public string Type { get; set; }

        public Nullable<bool> ISRead { get; set; }

        [Display(Name = "نام فرستنده")]
        [StringLength(50, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string SenderName { get; set; }
    
        public virtual User UsersFrom { get; set; }
        public virtual User UsersTo { get; set; }
    }
}
