//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Module : TimeEntity
    {
        public Module()
        {
            this.ModulePage = new HashSet<ModulePage>();
        }

        public int ModuleId { get; set; }

        [Display(Name = "نام ماژول")]
        [StringLength(50, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string ModuleTitle { get; set; }

        [Display(Name = "مکان ماژول")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int PositionId { get; set; }

        [Display(Name = "وضعیت ماژول")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public Nullable<bool> IsActive { get; set; }

        [Display(Name = "سطح دسترسی")]
        public string Accisibility { get; set; }

        [Display(Name = "نوع کامپوننت")]
        public int ComponentId { get; set; }

        public Nullable<int> DisplayOrder { get; set; }

        public virtual Component Component { get; set; }
        public virtual ICollection<ModulePage> ModulePage { get; set; }
        public virtual Position Position { get; set; }
        public virtual MenuModule MenuModule { get; set; }
        public virtual HtmlModule HtmlModule { get; set; }
        public virtual ContactModule ContactModule { get; set; }

        public virtual MultiPictureModule MultiPictureModule { get; set; }
    }
}
