//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NewsGallery
    {
        public int NewsGalleryId { get; set; }

        public int NewsId { get; set; }

        [StringLength(50, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string ImageName { get; set; }
    
        public virtual News News { get; set; }
    }
}
