//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Position
    {
        public Position()
        {
            this.Module = new HashSet<Module>();
        }
    
        public int PositionId { get; set; }

        [MaxLength(50)]
        [Display(Name ="موقعیت")]
        public string PositionTitle { get; set; }

        [MaxLength(50)]
        public string PositionName { get; set; }
    
        public virtual ICollection<Module> Module { get; set; }
    }
}
