//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductGallery
    {
        public int ProductGalleryId { get; set; }

        public int ProductId { get; set; }

        [StringLength(100)]
        public string ImageName { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
