//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductGroup : TimeEntity
    {
        public ProductGroup()
        {
            this.Products = new HashSet<Product>();
            this.AttributGrp = new HashSet<AttributGrp>();
            this.ProductRequest = new HashSet<ProductRequest>();
            this.DetailGroups = new HashSet<DetailGroup>();
        }
    
        public int ProductGroupId { get; set; }

        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [Display(Name = "عنوان گروه")]
        public string GroupTitle { get; set; }


        public Nullable<int> Depth { get; set; }

        public string Path { get; set; }

        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [Display(Name = "وضعیت گروه")]
        public Nullable<bool> IsActive { get; set; }

        public Nullable<int> DisplayOrder { get; set; }

        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [Display(Name = "گروه والد")]
        public Nullable<int> ParentId { get; set; }

        [Display(Name = "نام مستعار")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        //[Remote("Uniquealias", "Product_Groups", ErrorMessage = "این نام قبلا گرفته شده است، لطفا نام دیگری انتخاب کنید!", AdditionalFields = "GroupID")]
        public string AliasName { get; set; }

        public string type { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<AttributGrp> AttributGrp { get; set; }
        public virtual ICollection<ProductRequest> ProductRequest { get; set; }
        public virtual ICollection<DetailGroup> DetailGroups{ get; set; }
    }
}
