//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product_Attribut
    {
        public int Product_AttributId { get; set; }

        public Nullable<bool> isChecked { get; set; }

        [StringLength(100)]
        public string Value { get; set; }

        public Nullable<int> AttributItemId { get; set; }
        public int ProductId { get; set; }

        public virtual AttributItem AttributItem { get; set; }
        public virtual Product Product { get; set; }
    }
}
