//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductRequest
    {
        public ProductRequest()
        {
            this.RequestDetail = new HashSet<RequestDetail>();
        }
    
        public int ProductRequestId { get; set; }

        public string NAme { get; set; }

        public int ProductGroupId { get; set; }

        public int UserId { get; set; }

        [StringLength(150, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string status { get; set; }

        public string Descript { get; set; }

        [StringLength(150, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string Response { get; set; }

        [StringLength(150, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string details { get; set; }

        public Nullable<int> productID { get; set; }
    
        public virtual User Users { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
        public virtual ICollection<RequestDetail> RequestDetail { get; set; }
    }
}
