//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Product : TimeEntity
    {
        public Product()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
            this.ProductGallery = new HashSet<ProductGallery>();
            this.ProductTag = new HashSet<ProductTag>();
            this.Product_Attribut = new HashSet<Product_Attribut>();
            this.ProductDetail = new HashSet<ProductDetail>();
            this.StoresProduct = new HashSet<StoresProduct>();
        }
    
        public int ProductId { get; set; }

        [Display(Name = "نام محصول (انگلیسی)")]
        [StringLength(100, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string ProductName { get; set; }

        [Display(Name = "گروه محصول")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int ProductGroupId { get; set; }

        [Display(Name = "عنوان محصول")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [StringLength(100, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string ProductTitle { get; set; }

        [Display(Name = "تصویر محصول")]
        [StringLength(100, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string ProductImage { get; set; }

        [Display(Name = "نام مستعار")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [Remote("UniqueAliasName", "Product", ErrorMessage = "این نام قبلا انتخاب شده است، لطفا نام دیگری انتخاب کنید!", AdditionalFields = "ProductId")]
        public string AliasName { get; set; }

        public Nullable<int> GroupModel { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual ICollection<ProductGallery> ProductGallery { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
        public virtual ICollection<ProductTag> ProductTag { get; set; }
        public virtual ICollection<Product_Attribut> Product_Attribut { get; set; }
        public virtual ICollection<ProductDetail> ProductDetail { get; set; }
        public virtual ICollection<StoresProduct> StoresProduct { get; set; }
    }
}
