//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RequestDetail
    {
        public int RequestDetailId { get; set; }

        [StringLength(50, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string value { get; set; }

        public int DetailItemId { get; set; }

        public Nullable<int> ProductRequestId { get; set; }
    
        public virtual ProductRequest ProductRequest { get; set; }
        public virtual DetailItem DetailItem { get; set; }
    }
}
