//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class State
    {
        public State()
        {
            this.City = new HashSet<City>();
        }
    
        public int StateId { get; set; }

        [StringLength(50, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string StateName { get; set; }

        [StringLength(100, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string StateIcon { get; set; }
    
        public virtual ICollection<City> City { get; set; }
    }
}
