//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Store : TimeEntity
    {
        public Store()
        {
            this.UserStore = new HashSet<UserStore>();
            this.StoreTime = new HashSet<StoreTime>();
            this.StoreFollower = new HashSet<StoreFollower>();
            this.StoresProduct = new HashSet<StoresProduct>();
        }
    
        public string StoreId { get; set; }

        [Required(ErrorMessage = "لطفا {0} را وارد نمایید!")]
        [Display(Name = "شهر")]
        public Nullable<int> CityId { get; set; }

        [Required(ErrorMessage = "لطفا {0} را وارد نمایید!")]
        [Display(Name = "نام فروشگاه")]
        [StringLength(50, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string StoreName { get; set; }

        [Required(ErrorMessage = "لطفا {0} را وارد نمایید!")]
        [Display(Name = "آدرس")]
        [StringLength(300, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string StoreAddress { get; set; }

        public string Descriptions { get; set; }

        [StringLength(50, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string StoreIcon { get; set; }

        public Nullable<bool> IsActive { get; set; }

        [Required(ErrorMessage = "لطفا {0} را وارد نمایید!")]
        [Display(Name = "آدرس فروشگاه")]
        [StringLength(30, ErrorMessage = "لطفا تعداد کاراکترها را رعایت نمایید!", MinimumLength = 3)]
        //[Remote("UniqueSiteName", "Stores", ErrorMessage = "این نام قبلا ثبت شده است، لطفا نام دیگری انتخاب کنید", AdditionalFields = "StoreID")]
        public string SiteName { get; set; }

        [Required(ErrorMessage = "لطفا {0} را وارد نمایید!")]
        [Display(Name = "شماره تماس")]
        [StringLength(25, ErrorMessage = "لطفا {0} را به درستی وارد کنید!(نمونه : 09101112233)", MinimumLength = 10)]
        public string PhoneNo { get; set; }

        [StringLength(250, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string SiteAddress { get; set; }

        public Nullable<int> Favorite { get; set; }

        public Nullable<int> SeeStore { get; set; }
    
        public virtual City Cities { get; set; }
        public virtual ICollection<UserStore> UserStore { get; set; }
        public virtual ICollection<StoreTime> StoreTime { get; set; }
        public virtual ICollection<StoreFollower> StoreFollower { get; set; }
        public virtual ICollection<StoresProduct> StoresProduct { get; set; }
        public virtual StoreInfo StoreInfo { get; set; }
    }
}
