//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StoresProduct : TimeEntity
    {
        public int StoresProductId { get; set; }

        [StringLength(100)]
        public string StoreId { get; set; }

        public int ProductId { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:c}")]
        public Nullable<decimal> Price { get; set; }

        [StringLength(100)]
        public string OffPrice { get; set; }

        public Nullable<bool> IsActive { get; set; }

        [StringLength(100)]
        public string Color { get; set; }

        [StringLength(100)]
        public string linkSale { get; set; }

        [StringLength(100)]
        public string detail { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
