//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class StoreInfo
    {
        [Key,ForeignKey("Store")]
        public string StoreId { get; set; }

        public string banner { get; set; }

        public string ZindexMap { get; set; }

        public Nullable<double> latitute { get; set; }

        public Nullable<double> lngitute { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
