//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tbl_Help
    {
        public int tbl_HelpId { get; set; }
        [ForeignKey("User")]
        public int UserId { get; set; }

        public Nullable<bool> kihasti { get; set; }

        public Nullable<bool> kojai { get; set; }

        public Nullable<bool> chidari { get; set; }

        public Nullable<bool> kala { get; set; }

        public Nullable<bool> pishkhan { get; set; }

        public Nullable<bool> firsttime { get; set; }
    
        public virtual User User { get; set; }
    }
}
