//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshop.DomainClasses
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ticket : TimeEntity
    {
        public Ticket()
        {
            this.TicketMsg = new HashSet<TicketMsg>();
        }
    
        public int TicketId { get; set; }
        public int TicketGroupId { get; set; }

        [StringLength(50, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string Title { get; set; }

        [StringLength(50, ErrorMessage = "تعداد کاراکترها را رعایت کنید")]
        public string Status { get; set; }

        public int UserId { get; set; }
    
        public virtual TicketGroup TicketGroup { get; set; }
        public virtual ICollection<TicketMsg> TicketMsg { get; set; }
        public virtual User User { get; set; }
    }
}
